Planet:
    type: object
    config:
        fields:
            id:
                type: 'Int!'
            name:
                type: 'String!'
            astronauts:
                type: '[Astronaut]'